### ISSUE TITLE
can eups distrib give a more helpful failure message

### ISSUE THREAD

**Issue by danielsf** [RobertLuptonTheGood/eups#122]
I get a lot of users asking me to help them debug their `eups distrib install` failures.  None of them know where to find the test failure files (and I myself have forgotten where `eups distrib`'s build dir is, since it has been a long time since I had an `eups distrib install` build fail on me).  Could we modify `eups distrib` so that, when it fails, it says something like

`Failure log output to [whatever-the-build-dir-is]/tests/.tests/pytest-*xml.failed`

so that users unfamiliar with `eups` know where to find the relevant information?

**Comment by RobertLuptonTheGood** [comment]
I think it does tell you where the logs are.  The fact that they are in `tests/.tests/pytest-*xml.failed` isn't an eups thing, it's how pytest has been configured.

Can you check that the path isn't reported?  I'm happy to try to make it easier to see what's going wrong, but I'd rather not put build-system specifics into a build-system agnostic system like eups distrib

**Comment by timj** [comment]
That test output does also go to standard output so should be in the build log file created by `eups distrib`.

**Comment by danielsf** [comment]
Are you saying that it would be in `_build.log`?

**Comment by danielsf** [comment]
Never mind.  The person I was helping just confirmed that she got
```
Global pytest output is in /Users/Tina/lsst/stack/miniconda3-4.3.21-10a4fa6/EupsBuildDir/DarwinX86/sims_catalogs-2.3.7.1.sims+1/sims_catalogs-2.3.7.1.sims+1/tests/.tests/pytest-sims_catalogs.xml.failed
```
in `stdout`.  She just didn't see it (and I didn't tell her to look for it)

False alarm. Sorry for the noise.
