### ISSUE TITLE
version is not propagated to dependencies in `setup`

### ISSUE THREAD

**Issue by danielsf** [RobertLuptonTheGood/eups#128]
I'm not 100% sure that this is a bug, but it seems like odd behavior.

I have two packages, `sims_utils` and `sims_coordUtils`.  `sims_coordUtils` depends on `sims_utils`, among other things.  I want to use development copies of `sims_utils` and `sims_coordUtils`, along with a `current` version of the rest of the LSST stack built with `eups distrib install`.  I have cloned the two relevant repositories and labeled them with my username.
```
danielsf@cori12:~/sims_coordUtils> eups list sims_utils
   2.7.0.sims 	current sims sims_2_7_0 setup
   danielsf   
danielsf@cori12:~/sims_coordUtils> 
```
```
danielsf@cori12:~/sims_coordUtils> eups list sims_coordUtils
   2.7.0.sims 	current sims sims_2_7_0 setup
   danielsf   
danielsf@cori12:~/sims_coordUtils> 
```

If I run `setup sims_utils danielsf`, the correct version of `sims_utils` gets setup:
```
danielsf@cori12:~/sims_coordUtils> setup sims_utils danielsf
danielsf@cori12:~/sims_coordUtils> eups list sims_utils
   2.7.0.sims 	current sims sims_2_7_0
   danielsf   	setup
danielsf@cori12:~/sims_coordUtils> 
```

However, if I then run `setup sims_coordUtils danielsf`, the `current` version of `sims_utils` gets setup:
```
danielsf@cori12:~/sims_coordUtils> setup sims_coordUtils danielsf
danielsf@cori12:~/sims_coordUtils> eups list sims_coordUtils
   2.7.0.sims 	current sims sims_2_7_0
   danielsf   	setup
danielsf@cori12:~/sims_coordUtils> eups list sims_utils
   2.7.0.sims 	current sims sims_2_7_0 setup
   danielsf   
danielsf@cori12:~/sims_coordUtils> 
```

Is this expected behavior?  I am running version 2.1.4 of eups.

**Comment by danielsf** [comment]
Incidentally, I tried to fix this problem by declaring the packages with
```
eups declare -r . sims_coordUtils danielsf -t danielsf
```
but then, I get even weirder behavior.  eups does not appear to be honoring the `-t` tag
```
danielsf@cori12:~> eups list sims_coordUtils
   2.7.0.sims 	current sims sims_2_7_0 setup
   danielsf   	danielsf
danielsf@cori12:~> setup sims_coordUtils -t danielsf
No versions of sims_coordUtils are tagged danielsf; setup version is 2.7.0.sims
danielsf@cori12:~> 
```

**Comment by PaulPrice** [comment]
This is expected behaviour. If you `setup myProduct`, it will setup `myProduct` and all its dependencies. You probably want to use one of the `-j` ("just" this product) or `-k` ("keep" all products I've already setup) flags.

**Comment by danielsf** [comment]
Okay.  Thanks.
