### ISSUE TITLE
$EUPS_DIR/bin/setups.sh is not compatible with KSH in EUPS v1.3.0

### ISSUE THREAD

**Issue by airnandez** [RobertLuptonTheGood/eups#24]
The generated file $EUPS_DIR/bin/setups.sh does not work when using KSH:

    $ /bin/ksh eups/bin/setups.sh 
    eups/bin/setups.sh[34]: export: -f: unknown option
    Usage: export [-p] [name[=value]...]

Testing environment: Scientific Linux v6.5

**Comment by mjuric** [comment]
I think this has been fixed -- reopen if not!
