### ISSUE TITLE
eupspkg install to local eups repo?

### ISSUE THREAD

**Issue by CraigLoomis** [RobertLuptonTheGood/eups#29]
It can be useful to install a checked out product into a local eups repo. eupspkg install will do that, if asked politely. But a little bit of sugar and polish would help. If others agree and we can agree on where to put the sugar I'll submit a patch.

`eupspkg install -e -r` does most of the work we want. But there are a couple of desirable tweaks:

 * include `eupspkg decl -e -r`
 * allow forcing freezing of the table file -- some external install programs copy the ups dir.

Much of this could be done with a tiny `bin/eupsinstall` wrapper, basically:

> eupspkg install -e -r
> \# Somehow arrange to call eupspkg.sh's install_ups
> eupspkg decl -e -r

I'm wondering whether it would be good to pull out all the eupspkg functions into a common `lib/eupsfuncs.sh` for future development. Source that into eupspkg and eupsinstall, and add appropriate top-level optargs and logic.

Alternately, a couple more command line options to eupspkg would suffice. Getting dirty for a shell script.

*We'd also like to adjust TAG_REGEXP for other projects. Factoring out the component functions would help with that, too.*

**Comment by mjuric** [comment]
@CraigLoomis This issue hasn't seen activity for a while now -- I'm inclined to close it as I'm not sure if this is relevant any more. I still agree with the basic point -- that `eupspkg` functionality should be made more general and decoupled from `eups distrib`. I've come to think of it as a generic build abstraction system, that hides the details of the underlying build system (`make`, `scons`, `autoconf`, `CMake`, etc..). If I had the time, I'd largely split it out of EUPS and turn it into a package that EUPS uses to do builds, but that can also be used directly.
