### ISSUE TITLE
eups tags --clone gives "referenced before assignment" error

### ISSUE THREAD

**Issue by timj** [RobertLuptonTheGood/eups#47]
```
lsst-dev$ eups tags --clone b1535 current
eups tags: local variable 'tagNames' referenced before assignment
```
The problem is that `tagNames` is always printed out at the end of the `execute` function but it is only created in the `else` branch. `--clone` and `--delete` will trigger this.

Broken with commit 139f5ba0c426f8c3433788a4afbb7b0f88af26f3

**Comment by mjuric** [comment]
Fixed on 13f39300
