### ISSUE TITLE
Problem with eups distrib

### ISSUE THREAD

**Issue by garmilla** [RobertLuptonTheGood/eups#65]
When trying to run `eups distrib list pkg` I get the error:
```
NameError: "global name 'urllib' is not defined"
```
The error occurs in `eups/python/eups/distrib/server.py`. I just pulled and built yesterday, so I think I have the latest version of this file.

**Comment by timj** [comment]
@migueldvb I don't think #52 is quite right. It seems that in 296249b733750f24238276cb442efe7918398bef nothing is now importing the `urllib` package.

**Comment by timj** [comment]
The fix looks to be straightforward, just remove the `urllib.` prefixes.

**Comment by migueldvb** [comment]
Yes, I think that is right. I will remove those prefixes.
