### ISSUE TITLE
Python 3 doesn't quite work yet

### ISSUE THREAD

**Issue by timj** [RobertLuptonTheGood/eups#70]
Having a quick play with Eups using Python3. `lock.py` is currently using a `next()` method instead of a `next()` function (it has been allowed as a function since 2.6 but 3.x requires it to be a function and not a method).

My first attempt at `setup` leads to an error complaining that the arguments must be `str` and not `bytes`. 
Also seeing `'str' does not support the buffer interface`.

@migueldvb when you did the refactoring did you test it on Python3?

**Comment by migueldvb** [comment]
That is what I tried if I remember correctly. I will try again and report the results here.

**Comment by migueldvb** [comment]
Somehow I missed this problem. I seems that opening the output file in binary mode fixes the error in `setup`. @timj could you please test the changes in this branch?
