### ISSUE TITLE
Cannot declare packages: eups declare: Can't mix absolute and relative paths

### ISSUE THREAD

**Issue by r-owen** [RobertLuptonTheGood/eups#75]
If I install the current master fa02996 using

    ./configure --prefix=/Users/rowen/UW/LSST/lsstsw/eups/master --with-eups=/Users/rowen/UW/LSST/lsstsw/stack --with-python=/usr/bin/python
    make
    make install
    cd /Users/rowen/UW/LSST/lsstsw/eups/
    rm current
    ln -s master current

then setup my stack, I find that I cannot declare packages. For example:

    localhost$ eups declare -r . pipe_base git
    Warning: path /Users/rowen/UW/LSST/lsstsw/build/pipe_base is absolute, not relative to EUPS_PATH
    eups declare: Can't mix absolute and relative paths

This same error is also seen in many of the unit tests, e.g. if after installing eups as above I run "make install" in the original eups repo directory. I'm assuming lsstsw installs eups some other way, perhaps with a relative paty. But I also think eups should be robust enough to handle the above.

Note that the error occurs in the `commonpath` function in `utils.py`. I am very puzzled why that function cannot handle a mix of absolute and relative paths. One possible approach is run os.path.abspath on all inputs, so they are always absolute. That would be robust but it might upset other aspects of eups.

I'm also puzzled why the function `commonpath` exists instead of using `os.path.commonprefix`, and why `commonpath` uses uses card-coded values for path separator and current directory instead of using `os.path.split` and `join`.

**Comment by r-owen** [comment]
The following is an alternate implementation which works for me, but it normalizes the paths and I fear that may make some of eups unhappy.

    def commonpath(paths):
        """Given a sequence of path names, returns the longest common sub-path.
        """
        if not paths:
            raise ValueError('commonpath() arg is an empty sequence')

        paths = [os.path.abspath(path) for path in paths]

        split_paths = [splitpath(path) for path in paths]
        groups = zip(*split_paths)
        common_elts = []
        for group in groups:
            if any(g != group[0] for g in group[1:]):
                break
            common_elts.append(group[0])
        return os.path.join(*common_elts) if common_elts else ""

Note: this assumes eups can handle absolute paths in this comparison function, which needs testing. If it cannot, then a different solution is required. If this solution works it is simple and `os.path.abs` has the nice property that it also normalizes the paths, making the function more likely to give a correct and useful answer.

**Comment by RobertLuptonTheGood** [comment]
This implementation came from python3 with the odd fix.  It was requested by Colin Slater:

> I'm also running into eups declare mangling paths. In my case my $EUPS_PATH is /Users/ctslater/lsst, and I want to declare packages that live in /Users/ctslater/lsst_dev/pkgname. I think the line that KT linked to is indeed responsible, as it ends up declaring my packages as /Users/ctslater/lsst/dev/pkgname.
> 
> The problem is that os.path.commonprefix() is misleading and does a letter-by-letter comparison. There's a new function commonpath() implemented in python 3.5 that does the right thing, see http://bugs.python.org/issue10395. I suspect the best way to fix this is to copy the commonpath() implementation from that patch into eups and use that instead of commonprefix()

**Comment by r-owen** [comment]
@RobertLuptonTheGood it appears that the borrowed implementation is not appropriate for eups because of the explicit limitation that a mix of relative and absolute paths is forbidden. It replaces use of os.path.commonprefix which did support that mix, though based on a few tests it appears to always return "" in that situation. If that is truly wanted then a simple fix for os.path.commonprefix is suggested earlier on the thread you mentioned:

    def commondirname(paths):
        subpath = os.path.commonprefix(paths)
        for path in paths:
            if path == subpath:
                return subpath
        else:
            return os.path.join(os.path.split(subpath)[0], "")

I think it would be nice to do a better job with un-normalized paths (e.g. my implementation) but then there's the warning when declaring. I pushed my code to a branch of my fork named "fix75", but I didn't open a pull request due to the warning.

**Comment by r-owen** [comment]
Here is one possible solution. Use this replacement for the existing commonpaths function. I think it does everything it needs to, e.g. mimics os.path.commonprefix without the bug that caught Colin, yet also normalizes the paths:

    def commonpath(paths):
        """Given a sequence of path names, returns the longest common sub-path.

        This is a variant of os.path.commonprefix that offers two enhancements:
        - Input paths are normalized, so commonality is more likely recognized
        - The returned string always contains full path components, if it is not empty

        Like os.path.commonprefix, it returns an empty string if:
        - If there is no common path
        - A mix of absolute and relative paths is provided

        Based on code from Eric Snow http://bugs.python.org/issue10395
        """
        if not paths:
            raise ValueError("commonpath(%r): no paths provided" % (paths,))

        paths = [os.path.normpath(path) for path in paths]

        subpath = os.path.commonprefix(paths)
        for path in paths:
            if path == subpath:
                return subpath
        else:
            return os.path.join(os.path.split(subpath)[0], "")

I've tested it and it seems to work. Another option is to modify the existing function to return "" instead of raising an exception. Either would do the job. Note that the current code is also missing some "b" prefixes for strings.

**Comment by mjuric** [comment]
Is the last for loop equivalent to:
```
if subpath in paths:
    return subpath
else:
    return os.path.join(os.path.split(subpath)[0], "")
```
Btw., what does the last line do?

**Comment by RobertLuptonTheGood** [comment]
Sorry, I was lazy.  I'd be OK with reverting to my original code, or using something like Russell's.

**Comment by r-owen** [comment]
It turns out that commonprefix is only being used to test that one path is a subpath of another. There is a simpler and more efficient way to test for that: expand each path using os.path.realpath and then use startswith (being sure both paths ends with "/" to avoid the problem with os.path.commonprefix that caused all this fuss in the first place). Here is a function that works. I'll update the code to use it.

    def is_subpath(path, root):
        """!Return True if path is root or in root

        @param[in] path  path to a directory or file
        @param[in] root  path to a directory

        @note
        - path and root are both expanded to absolute paths with symbolic links resolved
        - does not test that root or path exist
        """
        path = os.path.realpath(path)
        root = os.path.realpath(root)
        if path == root:
            return True
        # append trailing slash to root to avoid "/a/bbb" being treated as a subpath of "a/b"
        return path.startswith(os.path.join(root, ""))

**Comment by r-owen** [comment]
I just implemented this and fixed one unit test and will make a pull request.

**Comment by r-owen** [comment]
Fixed using branch fix75
