### ISSUE TITLE
Unable to take exclusive lock warning

### ISSUE THREAD

**Issue by migueldvb** [RobertLuptonTheGood/eups#88]
I have used the default /usr/local prefix to install  files as root and get the following warning when I run `eups distrib install` as a non-root user. 
```
Unable to take exclusive lock on /usr/local; your command may fail
Unable to take exclusive lock on /usr/local/share; your command may fail
```
Should the root directory be writable by the user?

**Comment by RobertLuptonTheGood** [comment]
You can specify a lock directory in your ~/.eups/startup.py file:
`hooks.config.site.lockDirectoryBase = /tmp`
Or disable locking with --nolocks or by setting the lockDirectoryBase to None.  It's not totally obvious that a private lock is useful in a shared stack, and the locking is well known to be far too aggressive.

**Comment by migueldvb** [comment]
Thank you @RobertLuptonTheGood ,  with a lock directory eups distrib is working for me without the lock warning. Just for the record the directory lock in the startup.py file is enclosed in quotes using python syntax.
